### ISSUE TITLE
Provide a Dump.dat file

### ISSUE THREAD

**Issue by fgib1998** [Comer352L/FreeSSM#55]
Hey, i really like this project and would like to contribute if possible. After rigging up a suitable cable for my Legacy 3 from 1999, i was able to generate a dump file from my ABS/VDC ECU with the ROM-ID **79 BB D8**. Cruise Control wasn´t able to communicate and the HVAC isnt connected to a diagnostic port.

Is there any interest in this File? 
I wasn´t able to find the E-Mail Adress in the About Section mentionend in the "new SSM1 Definitions" thread.

**Comment by Comer352L** [comment]
For a 1999 Legacy:
**Engine**: uses the SSM2 protocol
**Transmission (automatic)**: either SSM1 ode SSM2
**ABS/VDC:** SSM1
**CC:** usually uses a different protocol variant which is currently not supported (and would require yet another interface)
**HVAC:** no diagnostic access (via SSM)

If you have automatic transmission and it uses SSM1, too, I would be interested in the dump file.
(for the email address, open the "About" dialog, select tab "Credits" and double click on "Comer352L")
For ABS/VDC, the dump file doesn't contain anything else than the ROM-ID.

Unfortunately, I don't have enough time at the moment to add support for the ABS controller.
It's on my ToDo list since a long time...

**Comment by fgib1998** [comment]
The automatic transmission and control module for it has been removed from the car a long time ago.
I may have the control module laying around somewhere and could rig something up to get a dump file from it, if the Transmission itself is not needed for it. Do you know if this would be enough or is the transmission required?

**Comment by Comer352L** [comment]
The transmission is not required, but some DTCs may show up.

**Comment by fgib1998** [comment]
I was able to generate a file and just send it to the e-mail adress.
